# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '9.0'

def pods_files
    pod 'XBButton'
    pod 'XBAlertViewBase'
end

target 'XBActionSheet' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  pods_files

  # Pods for XBActionSheet

  target 'XBActionSheetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XBActionSheetUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
